[project]
name = "scribloom"
version = "0.1.0"
description = "A daily prompt-based writing tool."
authors = [
    {name = "eyamagishi",email = "e.yamagishi0625@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
